import { jsPDF } from 'jspdf';

interface AuditResults {
  url: string;
  lighthouse: {
    categories: {
      performance: { score: number };
      accessibility: { score: number };
      seo: { score: number };
      'best-practices': { score: number };
    };
  };
  accessibility: {
    violations: Array<{ 
      id: string; 
      impact: string; 
      description: string;
    }>;
  };
  security: {
    isSecure: boolean;
    https: boolean;
    headers: Record<string, string | null>;
  };
  recommendations: {
    performance: string;
    seo: string;
    accessibility: string;
    security: string;
  };
  auditDate: string;
}

export function generatePDF(results: AuditResults): string {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  let y = 20;
  
  // Add title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Website Audit Report', pageWidth / 2, y, { align: 'center' });
  y += 15;
  
  // Add URL and date
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Website: ${results.url}`, 20, y);
  y += 10;
  
  const date = new Date(results.auditDate).toLocaleDateString();
  doc.text(`Audit Date: ${date}`, 20, y);
  y += 15;
  
  // Performance section
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Performance', 20, y);
  y += 10;
  
  // Create a score box
  const performanceScore = Math.round(results.lighthouse.categories.performance.score * 100);
  doc.setFillColor(getScoreColor(performanceScore));
  doc.rect(20, y, 15, 15, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text(performanceScore.toString(), 27.5, y + 10, { align: 'center' });
  doc.setTextColor(0, 0, 0);
  
  // Add recommendation
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  const performanceText = results.recommendations.performance;
  const performanceLines = doc.splitTextToSize(performanceText, pageWidth - 60);
  doc.text(performanceLines, 45, y + 7);
  y += Math.max(20, performanceLines.length * 7);
  
  // SEO section
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('SEO', 20, y);
  y += 10;
  
  // SEO score box
  const seoScore = Math.round(results.lighthouse.categories.seo.score * 100);
  doc.setFillColor(getScoreColor(seoScore));
  doc.rect(20, y, 15, 15, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text(seoScore.toString(), 27.5, y + 10, { align: 'center' });
  doc.setTextColor(0, 0, 0);
  
  // Add recommendation
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  const seoText = results.recommendations.seo;
  const seoLines = doc.splitTextToSize(seoText, pageWidth - 60);
  doc.text(seoLines, 45, y + 7);
  y += Math.max(20, seoLines.length * 7);
  
  // Accessibility section
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Accessibility', 20, y);
  y += 10;
  
  // Accessibility score box
  const accessibilityScore = Math.round(results.lighthouse.categories.accessibility.score * 100);
  doc.setFillColor(getScoreColor(accessibilityScore));
  doc.rect(20, y, 15, 15, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text(accessibilityScore.toString(), 27.5, y + 10, { align: 'center' });
  doc.setTextColor(0, 0, 0);
  
  // Add recommendation
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  const accessibilityText = results.recommendations.accessibility;
  const accessibilityLines = doc.splitTextToSize(accessibilityText, pageWidth - 60);
  doc.text(accessibilityLines, 45, y + 7);
  y += Math.max(20, accessibilityLines.length * 7);
  
  // Security section
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Security', 20, y);
  y += 10;
  
  // Security score box
  const securitySymbol = results.security.isSecure ? '✓' : '✗';
  doc.setFillColor(results.security.isSecure ? '#4ade80' : '#ef4444');
  doc.rect(20, y, 15, 15, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text(securitySymbol, 27.5, y + 10, { align: 'center' });
  doc.setTextColor(0, 0, 0);
  
  // Add recommendation
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  const securityText = results.recommendations.security;
  const securityLines = doc.splitTextToSize(securityText, pageWidth - 60);
  doc.text(securityLines, 45, y + 7);
  
  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  doc.setFontSize(10);
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.text('Generated by Website Audit Tool', pageWidth / 2, doc.internal.pageSize.height - 10, { align: 'center' });
  }
  
  return doc.output('datauristring');
}

function getScoreColor(score: number): string {
  if (score >= 90) return '#4ade80'; // green
  if (score >= 50) return '#f59e0b'; // yellow
  return '#ef4444'; // red
}
